package rules

import com.manuel.bootquartz.model.*

// Aprobamos a los que tienen 80 o más
rule "Age rule"
	salience 400
	when
		exam : ExamResult();
	then
		exam.calculateAge();
end

// Aprobamos a los que tienen 80 o más
rule "Milenial rule"
	salience 300
	when
		exam : ExamResult(exam.milenial == true);
	then
		System.out.println("HOLA!");
		exam.addMilenialBonus(10);
end

// Aprobamos a los que tienen 80 o más
rule "Initial rule"
	salience 20
	when
		exam : ExamResult(exam.percentage >= 85);
	then
		exam.setPassed(true);
end
